# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis coverage coveralls

# command to run tests, e.g. python setup.py test
script:
  - tox
  - coverage report
#  - coverage run --source pydftools -m py.test
#  - coverage report -m

after_success:
  - coveralls


# Calculate coverage
after_success:
  - ls -a
  - coveralls